### ISSUE TITLE
I like it! do you think it will work on steam deck?

### ISSUE THREAD

**Issue by smintman** [begin-theadventure/acfix-old#1]
I like your approach but (as I'm getting a steam deck) would be good to make sure we have an approach that works on that platform?

Do you think downloading steam-edit will run without anything else on a steam deck?

Maybe we would script to install steam edit as a flatpak? https://github.com/tijder/Steam-Metadata-Editor/tree/flatpak ?

Would also be good to introduce an option to install the "Common distributables" like I do on  assfix? as I think that is also a big reason things fail?

**Comment by begin-theadventure** [comment]
I think (appimage)[https://github.com/tralph3/Steam-Metadata-Editor/issues/15] would be enough.

**Comment by begin-theadventure** [comment]
I think [appimage](https://github.com/tralph3/Steam-Metadata-Editor/issues/15) would be enough.

**Comment by begin-theadventure** [comment]
or does it have flatpak already?

**Comment by begin-theadventure** [comment]
Ah there's a way to add it as an flatpak app, there's a script so I guess it should be hard to do?

**Comment by begin-theadventure** [comment]
Ah, there's a way to add it as a flatpak app, there's a script for that so I think it shouldn't be hard to do.
What about wget, is it available on Steam Deck by default?
What about python? Is it available on Steam Deck by default? Does flatpak version install python?

**Comment by begin-theadventure** [comment]
I think [appimage](https://github.com/tralph3/Steam-Metadata-Editor/issues/15) would be enough or maybe even better?
However if there is a way to add it as a flatpak app and there's a script for that, I think it shouldn't be hard to do.
What about wget, is it available on Steam Deck by default?
What about python? Is it available on Steam Deck by default? Does flatpak version install python?

**Comment by begin-theadventure** [comment]
Common Redistributables can be easily installed from the client or using `steam steam://install/228980` so I'll just add a info about it.

**Comment by begin-theadventure** [comment]
**Good news!
So I tried to package Steam Metadata Editor as an appimage but I failed :D
Buut there it is!: https://github.com/niess/python-appimage
I removed python and tk from my system and changed `./steammetadataeditor` -s to `./x.AppImage steammetadataeditor -s`.
And tk is only needed for GUI.
So the problem is (rather) solved but I will rename this issue to "Steam Deck Support" if anyone finds any problems or new ideas.

**Comment by begin-theadventure** [comment]
**Good news!**
So I tried to package Steam Metadata Editor as an appimage but I failed :D
Buut there it is!: https://github.com/niess/python-appimage
I removed python and tk from my system and changed `./steammetadataeditor` -s to `./x.AppImage steammetadataeditor -s`.
And tk is only needed for GUI.
So the problem is (rather) solved but I will rename this issue to "Steam Deck Support" if anyone finds any problems or new ideas.

**Comment by begin-theadventure** [comment]
**Good news!**
So I tried to package Steam Metadata Editor as an appimage and I failed :D
Buut there's this!: https://github.com/niess/python-appimage
I removed python and tk from my system and changed `./steammetadataeditor` -s to `./x.AppImage steammetadataeditor -s`.
tk is only needed for GUI.
So the problem's (rather) solved!

**Comment by begin-theadventure** [comment]
Okay but..
I actually wonder..
Steam has dependency python.

**Comment by begin-theadventure** [comment]
Steam depends on python and Steam Deck has it installed so there is no need for a workaround.. Closed.

**Comment by begin-theadventure** [comment]
lmao
